In [1]:
import open3d

Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.


In [2]:
from src.dataset import *

In [3]:
ds = Ds_point_model()

In [4]:
ds2 = Ds_point_sampled(ds)

In [6]:
ds2[0][1]

PointCloud with 2048 points.

In [9]:
import numpy as np

class_name, pcd = ds2[0]

points = np.asarray(pcd.points)
normals = np.asarray(pcd.normals)

print(f"Classe: {class_name}")
print("--- Primeiros 5 pontos (X, Y, Z) ---")
print(points[:5])
print("\n--- Primeiras 5 normais (Nx, Ny, Nz) ---")
print(normals[:5])

Classe: 02747177
--- Primeiros 5 pontos (X, Y, Z) ---
[[ 0.19480893  0.18885501  0.01102573]
 [-0.06682547 -0.38222599  0.13192914]
 [ 0.06505555 -0.05245627 -0.25022501]
 [ 0.18354377 -0.35137668 -0.11253842]
 [-0.15706627 -0.28259507 -0.14746419]]

--- Primeiras 5 normais (Nx, Ny, Nz) ---
[[ 0.          1.          0.        ]
 [ 0.          1.          0.        ]
 [ 0.          0.         -1.        ]
 [-0.85295775  0.          0.52197995]
 [-0.75960908  0.         -0.65037993]]


In [ ]:
class_name, pcd = ds2[0]

pcd.paint_uniform_color([0.5, 0.5, 0.5])

o3d.visualization.draw_geometries([pcd], window_name=f"Visualizando: {class_name}")

In [13]:
pip install matplotlib

  Using cached matplotlib-3.10.9-cp311-cp311-win_amd64.whl.metadata (52 kB)
  Using cached cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
  Using cached fonttools-4.63.0-cp311-cp311-win_amd64.whl.metadata (121 kB)
  Using cached kiwisolver-1.5.0-cp311-cp311-win_amd64.whl.metadata (5.2 kB)
   ---------------------------------------- 0.0/8.2 MB ? eta -:--:--
    --------------------------------------- 0.2/8.2 MB 3.1 MB/s eta 0:00:03
   - -------------------------------------- 0.3/8.2 MB 3.6 MB/s eta 0:00:03
   -- ------------------------------------- 0.5/8.2 MB 3.0 MB/s eta 0:00:03
   -- ------------------------------------- 0.6/8.2 MB 2.8 MB/s eta 0:00:03
   --- ------------------------------------ 0.8/8.2 MB 3.2 MB/s eta 0:00:03
   ---- ----------------------------------- 1.0/8.2 MB 3.4 MB/s eta 0:00:03
   ----- ---------------------------------- 1.1/8.2 MB 3.1 MB/s eta 0:00:03
   ------ --------------------------------- 1.3/8.2 MB 3.2 MB/s eta 0:00:03
   ------- --------------------


[notice] A new release of pip is available: 24.0 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [14]:
import matplotlib.pyplot as plt

In [18]:
path = "reconstructions\epoch_6_02747177_RECONSTRUCTED.ply"
pcd = o3d.io.read_point_cloud(path)
points = np.asarray(pcd.points)

o3d.visualization.draw_geometries([pcd], window_name=f"Visualizando: {path}")